version: '3.6'

services:
    redis:
        container_name: redis
        hostname: redis
        image: redis:latest
        command: --port 6379
        ports:
            - "6379:6379"
        expose:
            - "6379"
        restart: always

    web:
        container_name: web
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
        - "5057:5057"
        working_dir: /home/myproj
        volumes:
            - ./:/home/myproj
        links:
            - redis
        command: uvicorn main:app --host 0.0.0.0 --port 5057 --reload

    worker:
        container_name: worker
        build:
            context: ./
            dockerfile: ./Dockerfile
        working_dir: /home/myproj
        volumes:
            - ./:/home/myproj
        links:
            - redis
        command: rq worker --with-scheduler --url redis://redis:6379 my_queue